### ISSUE TITLE
Onboarding coop members

### ISSUE THREAD

**Issue by jimscarver** [rchain/Members#15] opened 2017-03-29 13:24 UTC
This epic is to meet the onboarding challenge from attracting members, educating them, accepting payment, identity proofing, facilitating cooperative involvement in the community and RHOC marketplace. Doug Rushkoff advised us that onboarding is our greatest challenge. When, if we experience exponential growth this process will need to be scalable.

Processes that are components of the onboarding process may be aggregated under this epic.

**Comment by patrick727** [comment] 2017-04-23 23:12
https://www.rchain.coop/coop-information-1 is the link to the drafted page for coop membership signup, i still link to the google form in this page because I like the new edits to the google form more than what squarespace is capable of in their form option. We should continue to explore a more privatized mechanism for collecting registration info

**Comment by plantether** [comment] 2017-04-24 00:18
"RChains" should be "RChain's", but should "RChains Platform" be "the RChain platform's"? Why is platform capitalized? Unless its formal name is going to be The RChain Platform, "platform" should have a small p. 

In "everyone can decide it's path" in the first section, "it's" should be "its"

I think "Pre-register to Become an Member" sounds better than "to Be a Member."

In the second section, why is "distribute-able" used instead of "distributable"?

In the second section, second paragraph, "and get to determine", "get" should be "gets," But it might sound better to say "and helps to determine" or "and gets to help determine."

In the third paragraph, I would change "to propose projects, budgets" to " to propose projects and budgets" and change "as well as helping to decide" to "and to help decide" so the sentence reads:
Being a member gives you opportunities to propose projects and budgets, and to help decide on governance related issues. 

I don't think "crypto" needs quotes around it.

There is a comma splice in the last line, "Spots" should not be capitalized," and usually numbers less than 10 are spelled out. I would suggest changing that to:
 
Two spots remain. Join the slack to learn more about when the vote will happen. 

I really like the colors and the spacing. The readability is good and the amount of information seems just right and it's all clearly written. I don't understand the reason for the emergency operations center picture in the beginning, or the guys in the hazmat suits. The pictures give a negative feel instead of a positive one.

**Comment by kitblake** [comment] 2017-04-24 13:12
On 24 Apr 2017 : 17, at 02:18, plantether <notifications@github.com> wrote:

[snip lots of eagle eyed text fixes]
> I really like the colors and the spacing. The readability is good and the amount of information seems just right and it's all clearly written. I don't understand the reason for the emergency operations center picture in the beginning, or the guys in the hazmat suits. The pictures give a negative feel instead of a positive one.
> 
Agreed on the negative feel. You could try moving the 'rocket under construction in the hanger' image to the top. It would set up the rocket science theme and it seems to be taken just before dawn.

**Comment by patrick727** [comment] 2017-04-24 13:53
@plantether, @kitblake, @jimscarver    [rchain.coop/coop-information-1](url) I took yesterday's feedback and updated the drafted page, let me know what you guys think, I did not add any more content on why co-ops are important because I agree with plantether and kitblake that the spacing and layout is good right now, but this we can finalize on wednesday!

**Comment by lapin7** [comment] 2017-04-24 20:13
I only see a grey page???

**Comment by lapin7** [comment] 2017-04-24 20:25
@plantether @kitblake @jimscarver @patrick727 
Let's delete the payment option in BTC and ETH for the moment, because we're not in sync with law.
 
Evan made a draft [COOP MEMBERSHIP AGREEMENT](https://docs.google.com/document/d/1iqhimjR38h-5mgv_km54wXrJkIK9PD7wzp_sXXOPIus/edit)
He also said in Slack PM:
... let me know if you want to add any terms or features be advised that we are going to have to apply to Washington DFI to actually do this and we are going to need to wait at least 10 days after we apply before we can start selling memberships

**Comment by patrick727** [comment] 2017-04-25 12:59
@lapin7 https://www.rchain.coop/coop-information-1 try that link. 

So are you suggesting that we take off the registration form for the time being? 

Also do you suggest that I link to the agreement on the info page or copy and paste the whole thing?

**Comment by lapin7** [comment] 2017-04-25 21:11
No. I suggest that we keep the registration form up, but that we mention that it's a draft exercise. 
I'm just saying that we have to keep the form up, because otherwise the issue is loosing attention.

And we have to discuss the legal document of Evan. For example I would like references to articles in Law with respect to what is written down in that doc. I mean legal stuff is fine, but there's not much law about crypto. If we try to be legally correct then we can wait for ages. I prefer to walk the confrontation way and not to wait for people who never have thought about crypto before ( I don't mean Evan hear, because he's very well into the subject.)

It would be nice if we could get Evan and Ed into this git hub chat. Greg would be welcome as well, but I think he has better things to do. When things are clear, we could send him a FYI.

**Comment by patrick727** [comment] 2017-04-26 13:01
i agree, it might be nice to get them into the members hangout today as
well. Then we could clear this up moving forward so that we can post the
page.

Cheers

**Comment by kitblake** [comment] 2017-04-26 14:22
On 26 Apr 2017 : 17, at 15:01, patrick727 <notifications@github.com> wrote:

> i agree, it might be nice to get them into the members hangout today as
> well. Then we could clear this up moving forward so that we can post the
> page. 

That's a nice setup that Evan made, gives us content to work with.

From a close reading, I imagine that Evan is not a lawyer, and I thought maybe a lawyer should look at this agreement. But I've 'been there, done that'. The lawyer will say, "This is a mess. We can't use anything. It needs a total rewrite! We just have to start from scratch." (Lawyers and software developers have a number of things in common. :)

However I like what HJ has said about getting things done and I'm sure we can think it through. Which, if a lawyer got involved, is what we'd have to do anyway.

Evan makes 6 points in as many paragraphs:

1. Once a year the Member will be eligible to receive a rebate of tokens, calculated as a percentage of tokens the Member used during the year.
2. Active Members are eligible to attend and vote at annual and special membership meetings.
3. Active Members are eligible to serve on a committee.
4. A new Member is required to pay a $20 fee. Active members must pay a $10 fee every year, [either as dues or] for services rendered.
5. Membership is nonrefundable and nontransferable.
6. Both the Member and the Coop will abide by Coop laws and articles.

In terms of onboarding, it's probably better to start the Membership Agreement by defining advantages, as opposed to beginning with the costs, so I shifted the fees item to #4 in the list above.

Are there any other points we need to have in the initial membership agreement?

HJ commented: Does the coop also say that members have a right to collaborate with others on projects that are beneficial for the coop?

Additional points or not, with a bit of polishing this could function as our initial membership agreement, for which we can elicit feedback from (future) members. Who may or may not be lawyers.

**Comment by lapin7** [comment] 2017-04-26 22:06
@4. A new Member is required to pay ........
Evan said in slack: be advised that we are going to have to apply to Washington DFI to actually do this and we are going to need to wait at least 10 days after we apply before we can start **selling** memberships

If we just could formulate "required to pay" into something that sounds less "selling" than we're good I think. So something like "donation" or whatever.

**Comment by patrick727** [comment] 2017-04-27 15:07
"Membership will be recognized after the dues have been accepted" ?? something like that could work to in regards to "required to pay" comment

**Comment by lapin7** [comment] 2017-04-27 21:13
Or we can put "required to pay (pending legal red tape)"

**Comment by kitblake** [comment] 2017-05-02 10:51
How about this formulation:
A new Member is expected to make a nonrefundable donation of $20 (pending legal red tape). In order to maintain active status, in succeeding calendar years the Member agrees to procure at least $10 worth of RChain products or services, or pay dues of that amount, else become inactive.

**Comment by kitblake** [comment] 2017-05-02 14:52
I'd like to suggest another way to handle the rebate of RHOC that Members will receive. The calculation is different but the end financial result for the Coop can be more or less the same, and IMHO it'll be much more appealing as there is potential for organic growth.

First the critique and then the suggestion.

Quote: "Every active member will get a share of the “net distribute-able surplus” generated by the cooperative in ratio to purchases made in that period. An active member is loosely defined as an individual who made at least $10 in purchases for that period."

There will be a lot of Members who either aren't particularly active, or they are active but don't make any 'purchases'. For those people the rebate will be minuscule. The percentage is not decided yet but assuming it's in the single digits, a rebate on $10 will be between $0.10 and $0.90 cents. Not much of an incentive. And for those who do regularly buy Coop resources, they will price in a rebate of x%  when ordering services.

Instead let's call it a 'payout'. It will be calculated as a percentage of the total RChain network throughput (or the sum of all RHOC transactions made on the blockchain during the period). That percentage can be multiplied by personal factors, such as expenditures on Coop resources and/or activity points earned.

Like a dividend for stocks, the payout will be larger if the RHOC value rises. It will also increase if the network turnover grows since that will effect a larger base sum in the calculation.

To work out the exact formula will require someone with a deeper knowledge of RChain and better math skills than I have. But it doesn't have to be nailed down now. The formula and percentage can be decided in the future. 

The important issue is to incentivize someone considering membership. We offer financial gains, albeit small, as a reward for collaboration, and the payout can potentially increase with the success of RChain.

So the quoted paragraph above could instead read like this:

"Every active member will participate in a yearly payout of RHOCs based on the total network throughput of RChain. The amount will be calculated as a percentage of network turnover multiplied by the RHOC price and a personal contribution factor."

Or something like that..

**Comment by lapin7** [comment] 2017-05-02 20:41
Yeah that's fine.
We must also get rid of the BTC payment option. Because it's cumbersome for
sending the 100 RHOC back. Could you delete that BTC question?
I hope to process the RHOC payments this week.
I also found that the payment addresses from the form are not always in
sync with the actual payments in ETH or BTC. I will come back to this later.

--
HJ

**Comment by kitblake** [comment] 2017-05-03 16:50
The BTC payment option is gone, guess you did it HJ. I made a few more fixes. 
FYI, I made a real payment, both to register and test. If need be we can use that tx for investigating.

**Comment by lapin7** [comment] 2017-05-04 05:52
Yes I deleted the btc option. 

Nice for the real test transaction. 

As you see there's a lot of activity without a lot of overview. So we need to have a kind of sympathetic guidance and get all into GitHub......

**Comment by kitblake** [comment] 2017-05-04 10:06
> As you see there's a lot of activity without a lot of overview. So we need to have a kind of sympathetic guidance and get all into GitHub...…


I'm perfectly happy using Github and its tools. Plus Github has the advantage that it's known and used by the developers. They have no learning curve. Means they can't duck it :)

Let's all start explicitly linking to Github issues in other channels, especially Slack. It's easy, either copy the url if you're in the web UI or copy the view it on GitHub link in the footer of the Github mails.

**Comment by kitblake** [comment] 2017-05-08 09:33
Here's a request for critique. This link is a share of the Coop Membership agreement, originally published by Evan Jensen: 
https://docs.google.com/document/d/1iqhimjR38h-5mgv_km54wXrJkIK9PD7wzp_sXXOPIus/edit?usp=sharing

I radically renovated Evan's work (which he spent time thinking through). The intention is to make the onboarding process as frictionless as possible. A contract, while indisputably necessary, can seem onerous and be a stumbling block. I added an existential intro, inspired by the Divvy DAO Operating Agreement, and modified the language to give it a more friendly and mentoring tone. 

Does it succeed? Should I ease off a bit or try to take it further? Feel free to suggest or edit, and in any case I have no problem with critique. 

Evan is not subbed to this issue. Despite our 'ask for forgiveness' approach, I feel that it would only be proper that I contact him personally and explain. I'll do that after the next iteration. 

The content of the original agreement can be found below the new text.

**Comment by optictopic** [comment] 2017-05-08 13:15
Nice work. Its is concise and clear. How many translations are going to be
made? Is Coop membership limited by any factors such as country of origin?
I assumed it wasn't since there was the 'emerging economy' consideration.

**Comment by kitblake** [comment] 2017-05-08 16:18
There's no plan for translations. If it was an app/Dapp maybe, but most crypto communities make do with english. I can't imagine we would bar any people from specific countries. 
The 'emerging economy' fee reduction is an idea that needs approval. In another project I'm working with a dev in the Philippines and $20 to him is like $100 to us. He would never join, but if it got reduced to a 'token' $2 then he might.

**Comment by lapin7** [comment] 2017-05-08 22:31
The fee is arbitrary. It serves more to get a personal ETH address in order to send workers more RHOC. We can also introduce a sponsor like system "Rich Pay For Poor". A Poor candidate member sends the smallest amount of ETH. A Rich member adds the needed amount if he/she thinks that the Poor candidate member has left a good motivation.

And another thing is a bonus like system for members who get extra rewards for their work. A kind of "Promis To Spend RHOC". So if your actual work get's a reward of 100 USD then you get for example 100 USD + 50 USD to spend on what you think is useful for the coop (all converted in RHOCs of course).

The whole goal is to get RHOC's into members hands. Let's say during 2017 we set as goal to get 500 mln RHOC into the hands of members. Those members should not sit on their RHOC's but get them in circulation, so that members get power to stimulate workers to do something good for the coop. In fact we have to create a RHOConomy.

**Comment by optictopic** [comment] 2017-05-09 00:03
Creating rewards can be tricky.  It requires creating a very detailed
description of what the coop needs or wants and a deadline to motivate the
competition.  Then finally the membership should vote on the contributions
where it is possible no entries are selected as winners and the reward is
held for another round of competition.  When it comes to membership for
those who can't otherwise afford it, a sliding scale with a probationary
period makes sense.  In other words those who would use this tool to spam
the membership channels could be easily removed.

I was an active part of the LTB community while it was cutting its teeth.
Creating micro economies can be quite burdensome, they are useful for
discovering how crafty people can be at gaming a system. The way I see
rhocs is they are nothing but gestating revs. I will have to see an
extremely compelling reason to part with them.

**Comment by kitblake** [comment] 2017-05-10 07:54
In order to accelerate RHOC distribution, why don't we do that 'RChain throughput payout' monthly, instead of once per year as currently envisioned? We could do it every month on the full moon (like today).

**Comment by lapin7** [comment] 2017-05-10 08:07
What is this RChain throughput payout?
Full moon distribution is also done at ByteBall. So tonight you get new
Bytes.

--
HJ

**Comment by kitblake** [comment] 2017-05-10 08:18
From the Membership Agreement:
> "...Once  a year, Member shall be eligible to receive an annual rebate of tokens expended during the previous year..."

Later I suggested using a different mode of distribution:
> "Every active Member will participate in a yearly payout of RHOCs/REVs based on the total network throughput of RChain. The payout amount will be calculated as a percentage of network turnover multiplied by the RHOC/REV price and a personal contribution factor."

Which I included in the modified agreement. 
(yes, it was inspired by Byteball's remarkable success :)

**Comment by patrick727** [comment] 2017-05-10 14:32
@kitblake @lapin7 

Id like t learn more about what byteball is even and why its so successful lol 

So your proposing that rewards for using the RChain be issued monthly? That's not a bad idea, but would need to be accepted by the BOD's

**Comment by lapin7** [comment] 2017-05-10 23:56
Byteball is a complete new view on how to get consensus about transactions
and how to form a new "blockchain". In fact it is no blockchain at all, but
any way a way of storing data in a decentralised and distributed manner. It
has no constraints on transaction volume per second. It's superfast. And it
can be adapted to existing views of doing business.

The whole thing is build by one genius person, based on Graph Mathematics
and very sound.

It has the potential to overcome the problems with Bitcoin, Ethereum and
even Rchain.

Rchain will become only successful when there are millions of stakeholders.
That means massive distribution on RHOC's. Change your mind and think for
example about a deal with McDonalds or Starbucks. When you buy a hamburger
or a cup of coffee, you would get the price in RHOC in your wallet.



--
HJ

**Comment by patrick727** [comment] 2017-05-11 14:22
That's super interesting, ill have to sign up for it here soon.

**Comment by kitblake** [comment] 2017-05-11 15:41
The tech is really innovative and the smart aspect of the Byteball distribution (besides the fact that they're giving away free money, which is rapidly increasing in value with every distribution round, a Gbyte is currently $272) is the 'why'. 

Here's a quote from the founder:
> "There will be no ICO, no crowdsale.  I believe the success of a currency depends on the number of people who own it, in fact Peter R’s research suggests that the historical marketcap of Bitcoin follows Metcalfe's law: https://bitcointalk.org/index.php?topic=572106.0,  i.e. it is proportional to the square of the number of active users.  That’s why I want Byteball to be in the hands of as many people as possible.

> 98% of all bytes and blackbytes (the private untraceable currency) will be distributed among bitcoin holders who link their bitcoin and byteball addresses before any of the distribution rounds.  No investment required, you keep your bitcoins, plus receive the bytes and blackbytes.  See below how to receive the coins."

https://byteball.org/

If anyone wants to participate the next distribution round is on the full moon of Friday, 9 June 2017, 13:09:36 UTC

**Comment by patrick727** [comment] 2017-05-11 16:38
This is more for personal chat channels, I reached out on slack, but I did set it up and am wondering what I need to do next in order to participate in the distributions?

**Comment by kitblake** [comment] 2017-05-11 17:33
(I replied on Slack so the Byteball participation convo can live there.)

The distribution model is the important point in terms of "Onboarding Coop Members". It would be great to figure out an enticing proposition where Members participate in the success of RChain.

**Comment by lapin7** [comment] 2017-05-12 07:20
Maybe [REI](https://www.rei.com/membership/benefits#) is a good example for Membership promotion. But [Aeternity](https://blog.aeternity.com/%C3%A6ternity-bounty-program-e6191d330cf5) is going more in the preferred direction.

**Comment by kitblake** [comment] 2017-05-12 10:44
REI is the model for our membership. Here are some things I notice:

- Recreational Equipment, Inc. sells outdoor recreation equipment. 
- They've existed since 1938!
- You can become a Member and get benefits. One benefit is a rebate on your purchases, which they call the Annual Dividend: https://www.rei.com/membership/dividend

About the Annual Dividend
- "Each March, active REI members receive their member dividend in the form of an Annual Dividend notice. The refund is typically 10% back on eligible REI purchases.*"

- "Only active members receive Annual Dividend notices."
- "To maintain your active status as an REI member, you need to make net merchandise or shipping purchases (purchases minus credits and returns) of at least $10 per year, unless you joined during that year."
- "Non-Dividendable Purchases from REI include: Sale items, items discounted 15% or more, REI Adventures trips, REI Outdoor School classes, sales tax, postage and the REI membership fee."

Following the REI model, we have a $20 Member fee and a requirement to spend at least $10 per year on equipment (not hardware equipment, but soft or wetware). Using REI as a precedent means they've done a lot work/research for us, and serves as some guarantee that it's all legal.

They also have stores in many states around the country, so the membership program must be legal in all states.

**Comment by lapin7** [comment] 2017-05-28 06:24
I'm kind of fed up with this Membership subject. It looks like a local affair for US-citizens. US-aliens are not considered at all. And probably membership only necessary in 2019.

**So let's move forward.** We could simply call people, who are involved now with RChain, **Activists**. 
They pay a fee of $20,00, in order to leave the trolls out.
They get get 100 RHOC. It's meant as a confirmation of their ETH-address.
They fill out the ["Activist registration"](https://docs.google.com/forms/d/e/1FAIpQLSecwGUVFNx_Xa_Qsw5bxLnaKstPS8kQnfrUGqpuf22rLDteDg/viewform)
If they work they fill out ("Job application"](https://docs.google.com/forms/d/e/1FAIpQLScJs4ea5G0Q3MRwuY3cSCfk9d8ZrkKUsUUq1jpX-m-5NhCfew/viewform) and they create ["Statement of Work"](https://docs.google.com/forms/d/e/1FAIpQLScI5HG_c4ISrlQgedcE_0rq27nMlrkfzzkib9XDcAvxM2hAlg/viewform).
If necessary they fill out taxforms like ["W9"](https://drive.google.com/open?id=0BwX0krsxHncTTUZFNVNJS3hyU3c), ["W4"](https://drive.google.com/open?id=0BwX0krsxHncTWWtJa1hKdDB3bms), ["1099"](https://drive.google.com/open?id=0BwX0krsxHncTZ0JnUWtoYlJHNlk)
Through Github\RChain\Members they pick up tasks/epics/issues and get a reward in RHOC.

_**How does that sound?**_
Please try it out if you haven't done so already :+

**Comment by patrick727** [comment] 2017-05-28 13:08
you may need the W8-BEN [](https://www.irs.gov/pub/irs-pdf/fw8ben.pdf ) 

Activists sounds like a good interim role to me.

**Comment by patrick727** [comment] 2017-05-28 13:12
Also the form still has "members" a lot, were you planning to change it to "activists"

Will deposit some eth and complete for testing soon.

**Comment by lapin7** [comment] 2017-05-28 21:22
Changing Member into Activist has some consequences at:
- google drive
- form
- github
and what else
Needs a careful approach

--
Cheers,
HJ

**Comment by kitblake** [comment] 2017-05-29 18:17
The term "Activist" works. I just posted a why in issue #19 

Let's preserve copies of the Member Registration/Agreement/forms etc because when we have REVs (in about a year, according to what Ed said in a recent meeting) then those documents can come into play. It'll also probably take a year to get permission to have a Membership Fee from all 50 US states. 

We need to figure out what the incentives for becoming an Activist are. I have some ideas, maybe others do to.

**Comment by kitblake** [comment] 2017-05-30 11:13
In an off-list discussion I saw the following:

> If the relation is B2B, then we could urge Activists for RChain to become a company and handle likewise. This would avoid contractor/employee problems.

This could be advantageous in many ways. Especially if the Trump tax plan gets implemented:
https://www.nytimes.com/2017/04/28/upshot/under-the-trump-tax-plan-we-might-all-want-to-become-corporations.html

>"For every child who grows up dreaming of having a limited liability company of his or her own, President Trump’s tax plan promises a dazzling future."

**Comment by patrick727** [comment] 2017-05-30 17:06
@kitblake I like the creativity. But, then the barrier is the set up costs and process to establishing an LLC, which isnt that bad, but its still a barrier.

Also an LLC is still an independent contractor it's just instead of submitting the w-9 info they submit the EIN info. 

There are definitely advantages, too me a good opportunity for a consultancy to work on.

**Comment by kitblake** [comment] 2017-05-30 17:30
What would happen if we said the Coop doesn't contract with individual persons (and all the related bureaucracy)? This is because of its DAO-like nature. 

Thus, an individual cannot receive more than $500. If a person expects to exceed that amount, then it has to be paid to a company with EIN info. Would that shift the burden of creativity? 

ps: I just realized that all the European contractors that my company has used are one-man companies.

**Comment by patrick727** [comment] 2017-05-30 17:54
Right, that's basically exactly what I went through in January. 

It just shifts the tax burdens to the LLC that's processing the deal, which if an opportunity for an entrepreneur to solve(and was also the idea behind livelygig and colony.io)

Which is another opportunity for individuals who work well together to ban together like mercenary groups and sell their services like teams. @plantether and I have had convos about that, distributed research groups or pirate parties lol

**Comment by kitblake** [comment] 2017-06-02 17:12
I'd like to propose a distribution method to get RHOCs out there. (If it sounds familiar, I posted [an idea](https://github.com/rchain/Members/issues/15#issuecomment-298659138) about a month ago in #15 but the Membership drive has been derailed by the state-by-state applications process.) 

The approach is based on Byteball (http://byteball.org/) who are giving coins away for free. They believe digital currencies follow Metcalfe's Law, where the market cap of a currency is proportional to the square of the number of users. True or not, as of this writing Byteball is #35 on https://coinmarketcap.com/currencies/. [The tech is interesting too, their blockchain is a Directed Acyclic Graph, which solves the consensus problem in an entirely different way than proof of work/stake.]

The fair distribution model Byteball is using doesn't fit our use case so this proposal sketches a different method. However, if you own some BTC you really should check Byteball out, and not just for the learning curve. They are giving away free money – literally – and people I know are becoming wealthy from it. The next dist is the 9th of June. 

So, the RChain variant: when someone becomes an Activist they get 100 RHOCs. Then, next month, they get more RHOCs. How many? Well, that depends on how active they've been and how busy the RHOC blockchain has been. Here's a description:

> “Every RChain Activist will participate in a monthly payout based on the total network throughput of RHOCs. The amount will be calculated as a percentage of network turnover multiplied by the RHOC price and a personal contribution factor.”

Like a dividend for stocks, the payout will be larger if the RHOC value rises. It will also increase if the network turnover grows since that will effect a larger base sum in the calculation.

If an Activist does nothing, s-he will still get some RHOCs. Figuring out the exact formula will require discussion, some math, and an oracle or two. But the formula is not the point. 

The intention is to incentivize people to become Activists. We offer financial gains, albeit small, as a reward for collaboration, and the payout will increase from both personal contributions and the success of RChain. 

Thoughts?

**Comment by lapin7** [comment] 2017-06-17 09:14
The form for Activist registration has been cut down to one question.
[Rchain website](https://www.rchain.coop/coop-information-1#coop-information)
[Form](https://docs.google.com/forms/d/e/1FAIpQLSecwGUVFNx_Xa_Qsw5bxLnaKstPS8kQnfrUGqpuf22rLDteDg/viewform) The intro of this form may need additional editing.

Because of a leak to a google doc that contained personal info. For all collecting of data we need now approval of Evan, because a large data breach would certainly be a first class clusterfuck that would be extremely demanding of time and money. In the future we must not set up processes to collect payments or personal information from anyone without express instructions.

[Addititonal info about data breach](https://drive.google.com/open?id=0BwX0krsxHncTRy10SHNYU1RGU2ZpLWplRTlaOHVkaVJ2WUNv)

So we need to be careful for setting up processes:

- how to become an active involved Activist
- how to create a Statement of Work (SoW)
- how to approve a SoW
- how to suggest projects/tasks
- how to allocate a budget to projects/tasks (only rewarded with RHOC)
- how to approve a request for declaration
- how to approve an invoice and payment
- how to record the expense
- how to go about the collecting of tax-forms (W-9, W-4) for independent contractors

**Comment by kitblake** [comment] 2017-07-13 16:02
Creating workflows will help to organize the many processes we're dealing with. I'll take a shot at the first item, "how to become an active involved Activist", which overlaps into the second, "how to create a Statement of Work (SoW)". These actions are mentioned in the FAQ #60 and it would be good to have them clarified before the FAQ becomes public.

**Comment by kitblake** [comment] 2017-07-14 18:09
![onboarding_workflow](https://user-images.githubusercontent.com/912545/28224654-3ee4ad44-68d0-11e7-9399-382d24888fe3.png)

**Comment by kitblake** [comment] 2017-07-14 18:13
There might be (should be) more event sources. Also this is still somewhat linear, as it assumes that after becoming an Activist the next step must be to fill out the Talent Pool form, while in fact an Activist could skip that and go directly to the SoW form. Will we allow that... that's the question.

**Comment by lapin7** [comment] 2017-07-20 00:52
Both the talent pool and sow serve in my opinion to get an idea of what an activist could do and to get a more formalised relation with the activist. After it depends on the activist what s/he is going to take on for tasks and if that task is rewarded in RHOC. 

So the fastest way to leads to an sow is the best, I think.

**Comment by kitblake** [comment] 2017-07-25 09:29
Yes, let's create the path of least resistance. I adjusted the diagram.

**Comment by jbassiri** [comment] 2017-08-03 17:51
Feedback is welcome on initiation and annual member incentives outlined in sheet attached here!

Clearly, this is a thought experiment. The only way I see membership working to scale (1B members +) is if even 1/100,000,000th of a Rev (what I'm calling "Dust") becomes a useful value (in my model I have $10 bucks). That's the only way there'll be enough Rev value (given the assumptions) to go around as incentive and annual dues for the foreseeable future - say ~1000 years. 

This is only possible because crypto is so divisible, from what I understand, to the 100,000,000th digit.

[This is a thought experiment because] I'm not sure it's realistic to have each single Rev be worth $1B and the Rev valuation to be at $870 Quadrillion by some far out future date (in my model 2050). 

By the same token, however, someone from the Middle Ages would be spooked that $200T+ of fiat currencies, stocks, and bonds rule all transactions in the world. They'd be like "what's fiat, stocks, and bonds" and how do I put "200T of anything" into perspective... I think blockchain will get us to "quadrillions of value" -- even though its hard to comprehend today.

I suggest with the legitimacy behind Greg's vision of Rchain and this community - Rev could be what takes humanity to the world of tomorrow, a better world for all. 

I still believe in dApps and other tokens, but I think money is still a fundamental "dApp" so to speak and one coin will end up being the most convenient [read: stable] store of value -- no matter how good exchanges become they won't be able to exchange legitimacy, stability, governance, concurrency :1st_place_medal: 

The analogy I've used before is: any group of people can say they're starting a new country with a document called the Declaration of Independence and a Constitution. But there's still only 1 USA. What's happening today with Rchain, I think, is truly on that level of special. 

[08.03.17 Jacob's Thought Experiment - Global Membership Growth Plan.xlsx](https://github.com/rchain/Members/files/1198087/08.03.17.Jacob.s.Thought.Experiment.-.Global.Membership.Growth.Plan.xlsx)

**Comment by kitblake** [comment] 2017-08-04 09:59
What an extrapolation! :) But who knows, it could happen. Nice that you made a sliding scale that keeps the Incentive/Income totals constant thru the years. 

I noticed that the Incentive and income results are keyed to the REV value. Some might say that $1,000,000,000 in the future is optimistic ;) so I added formulas in the result cells. Now if you input a different value for the "Future Price of Rev (USD)", the results alter accordingly. So pessimists can also do calculation and input, say, $50000. Anybody who wants to try it can do it in this Google sheet: https://docs.google.com/spreadsheets/d/121h9k2xxv4l7wEgQz_3OcGiG9iGRd-e6b1cti_gXcQc/edit?usp=sharing

**Comment by lapin7** [comment] 2017-09-15 08:44
@optictopic 

And please add yourself as collaborator to this rep by reacting on the [invite](https://github.com/rchain/Members/invitations)

You could then be rewarded with RHOC for you TIME-participation

**Comment by jimscarver** [comment] 2017-12-26 12:47
onboarding krishna to myetherwallet and metamask https://youtu.be/S1b8x4NxwtA
it turned our he knew nothing about rchain or blockchain but wants to learn and earn.
What are recommended videos or other resources for this task?

**Comment by dckc** [comment] 2018-01-08 00:33
Ooh! a recording of onboarding. Nice, @jimscarver !

The work I did on README.md CONTRIBUTING.md  was my answer to "What are recommended videos or other resources for someone who wants to learn and earn?" But it didn't occur to me that somebody might be interested in rchain without being somewhat familiar with Ethereum and bitcoin.

**Comment by patrick727** [comment] 2018-01-09 16:27
I second that!

I tend to connect rchain to those to as an entry.

good work @jimscarver

**Comment by dckc** [comment] 2018-01-15 20:54
https://github.com/rchain/Members/blob/master/membership/assets/Onboarding_Workflow.png starts with "new user joins slack" which is clearly out of date. Should I delete that diagram?

It's not straightforward for me to updated it because the editable source version isn't checked in.

**Comment by lapin7** [comment] 2018-01-26 11:52
Continues with [#253](https://github.com/rchain/Members/issues/253)

**Closed by lapin7** 2018-01-26 11:52 UTC
Labels: Marketing, MatterMost Migration, Operations

**Comment by Keaycee** [comment] 2018-01-28 15:17
Onboarding  can be a challenge as some people or coop members don't like to be KYCED. This thread is related to #222

**Comment by lapin7** [comment] 2018-01-29 09:23
They don't have to in order to collaborate.

--
Cheers,
HJ
