### ISSUE TITLE
O> Github issue voting

### ISSUE THREAD

**Issue by lapin7** [rchain/Members#85] opened 2017-08-19 13:48 UTC
Jake's voting mechanism for Issues on GitHub
https://github.com/Jake-Gillberg/git-vote

**Comment by lapin7** [comment] 2017-08-19 14:03
@Jake-Gillberg Hi,
I've been looking at your App "Github voting chrome extension'. Great work !!
Maybe work can be combined.

I'm busy with decentralised budget allocation for GitHub issues by making use of Google forms and Gsheets. Your App could be of great use.

Is it possible to add an amount to the vote. And that the vote averages out all the votes?
The amount is an estimate of an Activist for the amount of RHOC needed for an issue to be resolved. S/he thinks about the number of hours that is needed and multiplies it with $40 (hour rate for Activist). 

When there are more then 3 Activist that have estimated the budget for an issue, then the Coop can allocate this budget and the Activist can do work for resolving the issue.
Through [Gform 'RChain Activist RHOC Distribution'](https://docs.google.com/forms/d/1wfMRzDxytIBuDP20Va4j2aE4ei-LhRLOOuBr4-96iRA/edit) the Activists can estimate their effort on an issue. That estimate is peer controlled by Peer Activists. When there is at least 1 Peer that has given an opinion about the amount and quality of 'work done' and about which percentage that would take out of the budget. Then the Coop can transfer the number of Rhoc.

Cheers HJ

**Comment by Jake-Gillberg** [comment] 2017-08-23 06:04
@lapin7 Hey HJ,

Yes, something like the git-vote tool could be modified to do some of the work that the current bounty system is doing.

Can you explain more to me the advantages of doing this via a smart-contract vs the way we are doing it now? What do you hope to gain with a git-vote like tool doing bounty reward estimates / allocations / distributions?

**Comment by lapin7** [comment] 2017-08-23 11:44
You're right. The advantage is not big. Let's first tryout the Gsheet system and the up voting through the smart contract. 

Best,
HJ

**Comment by lapin7** [comment] 2017-08-23 11:59
Great
Some issues have been allocated a budget. 
Now The second step. 
That's awarding rewards to activists on those issues that have a budget. 
It can be done through form 
https://docs.google.com/forms/d/1wfMRzDxytIBuDP20Va4j2aE4ei-LhRLOOuBr4-96iRA/viewform?edit_requested=true

Or the gsheet "RChain Activist RHOC Distribution" tab "RHOC rewards August 2017"
https://docs.google.com/spreadsheets/d/1wD8DzlvXZCtfycToN0K506Kev4oJm8yvosY0FIHZiYM


Best,
HJ

**Comment by kitblake** [comment] 2017-09-17 11:07
The git-vote component, built to work with Metamask, also works with Parity. Currently this issue has 4 votes. Two of those were made with Parity.

Steps to reproduce:
• Configure your Parity to run on the Ropsten testnet in Settings > Parity.
• Assuming you have test ETH/RHOC in Metamask, transfer some to your Parity wallet (if not, ask @jake_gillberg to send you some).
  - The ETH can be transferred to your Parity address via Metamask.
  - The RHOC can be transferred using MyEtherWallet:
     1. Go to MyEtherWallet.com
     2. Change the Network setting in the header to Ropsten.
     3. Click “Send Ether & Tokens”
     4. Click “MetaMask / Mist”
     5. Click “Connect account".
     6. Once it's connected to your Metamask, "Add Custom Token" with:
       - Contract: 0xb55d53e953e4B81BA637B9Fe16e17D11233f5fB1
       - Symbol: RHOC
       - Decimals: 8
     7. Under "Amount To Send", click the currency name and select RHOC.
     8. Generate transaction and send RHOC to your Parity wallet.
• Vote.

**Comment by lapin7** [comment] 2017-09-17 13:01
Oh me, dummy :-(

What does @jake_gillberg need to be able to send me Test Tokens?
What must I do to receive those tokens?

--
Cheers,
HJ

**Comment by kitblake** [comment] 2017-09-17 17:58
Using Chrome (not Firefox because you need the git-vote Chrome extension), set your Metamask or Parity on the Ropsten testnet, then send Jake your address.

**Comment by kitblake** [comment] 2017-09-20 10:56
There are a few decisions to be made before we take any next steps on a code level. However I also want to remind everyone that one of our objectives is KISS. Voting can get ridiculously complex. Feel free to debate or amend:

> Intention: RChain Activist/Members who have checkin rights in the Members repo can vote on issues. Issues with higher vote counts get front burnered. 

* Do we want to charge more, like 1 RHOC, in order to vote? 
  - If so, what should happen with the collected RHOCs? 
* Do we care that people can vote more than once? 

I'll post what I think later. For now, are there any other important issues to be added to this list?

**Closed** 2018-01-12 21:05 UTC
Labels: Governance, MatterMost Migration
