### ISSUE TITLE
Translate the 4 blog post to French 

### ISSUE THREAD

**Issue by BelovedAquila** [rchain/Members#907] opened 2018-08-16 00:19 UTC
### Benefit to RChain

Reach larger audience and help to build the community
Translated contents will be posted both on  <a href="https://rchaincommunity.xyz/">RChain Worldwide Community Forum > French (Français) > Blog</a>, and [Medium Blog](https://medium.com/@fidzy10) 

### Original (English) Content
- [RChain Spotlight : Translo](https://blog.rchain.coop/rchain-spotlight-translo/) (616 words, $117.40)
- [Computational Calculi Primer](https://blog.rchain.coop/computational-calculi-primer/) (1,523 words, $253.45)
- [RChain Asia :China](https://blog.rchain.coop/rchain_asia_china/) (578 words, $86.70) 
- [Computational Calculus Primer Part 3: ρ-calculus ](https://blog.rchain.coop/calculus-primer-ρ-calculus/) (2584 words, $371) 

### Translated (French ) Content
- [RChain Spotlight : Translo](https://rchaincommunity.xyz/t/rchain-spotlight-translo/397)
- [Introduction aux calculs informatiques:lamda calculus & BNF](https://rchaincommunity.xyz/t/introduction-aux-calculs-informatiques-lamda-calcul-amp-bnf/411)
- [Rchain Asie:chine](https://rchaincommunity.xyz/t/rchain-asie-chine/412) 
- [Introduction Aux Calculs informatiques partie 3: ρ-calcul](https://rchaincommunity.xyz/t/introduction-aux-calculs-informatiques-partie-3-calcul/483) 
_Estimated Budget of Task:_ **5,298 Words $[794.70]**
_Estimated Timeline Required to Complete the Task:_ **[2weeks]**
_How will we measure completion?_ **[ Fill the Translated (French) Contents section above ]**

### Legal

_Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws._

### Translation Checklist

*for non translation issues, delete this section*

  - Why translate this document?
    - It's important to translate because ____
    - [x] It's an RChain blog item on [Medium](https://medium.com/rchain-cooperative)
    - [x] It's an RChain blog item on https://blog.rchain.coop/
    - [ ] It's a document on https://developer.rchain.coop/ that has been endorsed
          for translation by @Jake-Gillberg, @MParlikar, or @KellyAtPyrofex 
  - How can people who do not speak this language be assured of the quality of the translation? (all are required)
    - [x] several reviewers are involved (_assign the ticket to them_)
    - [x] at least two of them have high proficiency in _the target language_
    - [x] at least two of them have high proficiency in English
    - [x] at least two of them have either
       - [x] formal training: degree / certificate: ___ from institution: _____ 
        B.A in French from Nnamdi Azikiwe University, Delf certificate Ministry of National Education France
       - [x] a track record of quality work on rchain bounties: #653 , #464, #623  ...
       - [ ] another body of work readily available for community review: _____
  - What about maintenance? (choose one)
    - [x] the source document is stable; further translation work is not expected
    - [ ] our plan to keep the translation up to date is: ____

_**Word counting and pricing for translations will be done with [The World's Fastest Human Translation Service](https://customer.stepes.com/instant-translation-quote/#)**_

**Comment by casanwugo** [comment] 2018-08-17 02:35
Hello @BelovedAquila...  Those are already been translated in #889. Please feel free to collaborate over there, rather than opening another similar issue with the same goal. This is in order to prevent duplicate of work. Thank you.

**Comment by BelovedAquila** [comment] 2018-08-17 05:08
@casanwugo  they were not there when this issue was created, did you edited it and added it up or something?

**Comment by casanwugo** [comment] 2018-08-17 06:38
I update as the documents come up... Hence the issue in review for 3weeks. 

A "Translate into French" issue is currently open. Why open another rather than collaborate on the ongoing?

**Comment by BelovedAquila** [comment] 2018-08-17 08:35
@casanwugo That A "Translate into French" issue is open doesn't entail another can't be opened, since it contains a different content.

>Why open another rather than collaborate on the ongoing?<

I find it interesting that you are asking this question, because before opening this issue, I asked to collaborate but you refused it.

**Comment by casanwugo** [comment] 2018-08-17 18:03
![screenshot_20180817-162313](https://user-images.githubusercontent.com/38157040/44276592-d8e00700-a23f-11e8-9a24-ed7a8a245a98.png)

Kindly point to me my refusal in this conversation?

With all due respect..,Your last translation was a controversial one that is yet to be approved by the guides, and you did ask me to collaborate of which i declined because looking up the project, i wasn't sure of its genuineness,,..one of the reasons am skeptical about collaborating with you.

My works are not copy and paste. They are not google translate either. I put in lots of hard work and effort to make French translations look best because these are valuable RChain documents... I'm no translation guide, but i have made it my committment to ensuring that no French document is archived on a 'bad work' record going forward.

With these points noted, i'll like to end by reminding us that as RAMs, working together for the benefit of the coop is key, and so, would ask you to collaborate with @casanwugo, @philipandri002, and others only on the basis that you have greatly improved in your level of professionalism in translating French documents.

**Comment by BelovedAquila** [comment] 2018-08-17 18:48
@casanwugo That was actually our conversation, and it looked like a refusal, am sorry if it wasn't. The issue with the last translation wasn't with the translation but with its arrangement, we learn and make adjustments.

**Comment by AyAyRon-P** [comment] 2018-08-21 14:16
@BelovedAquila @casanwugo 

Has this GitHub issue duplication been resolved? I find it in the best interest of the coop to have more reviewers whenever possible to ensure quality and accuracy of the translation. 

Please let me know if I need to mediate this issue further.

**Comment by BelovedAquila** [comment] 2018-08-21 14:30
@AyAyRon-P I and @casanwugo resolved on me finishing this which has already been opened and afterwards closing it and collaborating on #886 subsequently.

**Comment by BelovedAquila** [comment] 2018-08-30 08:12
@AyAyRon-P @Pavlos1851 @casanwugo please I need help in understanding how the words and worth is calculated please, so I did be sure I am not overestimating or underestimating please, Thank you

**Comment by AyAyRon-P** [comment] 2018-09-04 15:00
@BelovedAquila Did you change the blog posts from what @casanwugo did in #889? So this issue #907 and the one she did are different correct? 

Please use this tool to calculate the translation. https://customer.stepes.com/instant-translation-quote/#

**Comment by BelovedAquila** [comment] 2018-09-04 20:05
Yes @AyAyRon-P they are absolutely different, but as from next month I and @casanwugo did be working on a single issue. Thank you

**Comment by BelovedAquila** [comment] 2018-09-08 14:36
@AyAyRon-P @Pavlos1851 Please I need your votes, thank you

**Comment by jimscarver** [comment] 2018-09-08 15:38
spot checking translation back to english the translation seem to be if good quality so I will support this issue.

**Closed as completed** 2018-10-05 21:22 UTC
Labels: zz-Translation
